#pragma kernel DirectionPull_Vertex

StructuredBuffer<float4> _Direction;
StructuredBuffer<float3> _Vertex;
RWStructuredBuffer<float4> RW_Result;
[numthreads(1024,1,1)]
void DirectionPull_Vertex(uint3 id : SV_DispatchThreadID)
{
	float3 pull = RW_Result[id.x].xyz;
	float3 vertex = _Vertex[id.x];
	float3 direction = _Direction[id.x].xyz;
	float4 res = float4(vertex + direction * pull, 0);
	RW_Result[id.x] = res;
}